name = "Meowtys S4"
author = "Hilha"
version = "5.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7709baec32882147df657bbe1f6174b45882efe545e963bc520dc9c651206c19"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
