name = "Meowtys S4"
author = "Hilha"
version = "5.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dbc1c15bff376e11081a8c5cf74360c704c000313a5f99cd3b4f48a1e551f051"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
