name = "Meowtys S4"
author = "Hilha"
version = "5.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5cbf1d589badcc6e9d676861d03f9a520899bfe7e5fa7616115f21184c347fc4"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
